### PR TITLE
Upgrade to oculus sdk v32

### PR DESCRIPTION
**Pull request by pellet**
I used libovr.shutdown() without any issues but I did not try using opengl - Let me know if you'd like me to test this to see if the crash has been fixed.
I used psychxr in monoscopic/headlocked mode to draw images in front of the user.
Thanks for your great work on this project :)

### CODE REVIEW

**Comment by mdcutone** [comment]
Glad you like PsychXR! Thanks for the PR, I'll take a look at it and do another release.

**Comment by mdcutone** [comment]
Hoping to get a build done this week, been busy working on other things.

**Comment by pellet** [comment]
thanks, let me know if you want some help with the testing.

**Comment by mdcutone** [comment]
This is taking longer because I need to redo the build system.

**Pull request merged**
